//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Resources
{
    [Serializable]
    public class CheckScheduleRequest : Message
    {
        public const string k_RosMessageName = "xrrover_backend/CheckSchedule";
        public override string RosMessageName => k_RosMessageName;

        public string zone;

        public CheckScheduleRequest()
        {
            this.zone = "";
        }

        public CheckScheduleRequest(string zone)
        {
            this.zone = zone;
        }

        public static CheckScheduleRequest Deserialize(MessageDeserializer deserializer) => new CheckScheduleRequest(deserializer);

        private CheckScheduleRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.zone);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.zone);
        }

        public override string ToString()
        {
            return "CheckScheduleRequest: " +
            "\nzone: " + zone.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
