//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Resources
{
    [Serializable]
    public class CheckScheduleResponse : Message
    {
        public const string k_RosMessageName = "Resources/CheckSchedule";
        public override string RosMessageName => k_RosMessageName;

        public bool occupy;
        public string message;

        public CheckScheduleResponse()
        {
            this.occupy = false;
            this.message = "";
        }

        public CheckScheduleResponse(bool occupy, string message)
        {
            this.occupy = occupy;
            this.message = message;
        }

        public static CheckScheduleResponse Deserialize(MessageDeserializer deserializer) => new CheckScheduleResponse(deserializer);

        private CheckScheduleResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.occupy);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.occupy);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "CheckScheduleResponse: " +
            "\noccupy: " + occupy.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
